import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#1b1c1c',
        'on-surface': '#1b1c1c',
        'secondary-fixed-dim': '#ffb694',
        primary: '#003569',
        'inverse-primary': '#a7c8ff',
        'primary-fixed-dim': '#a7c8ff',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'inverse-on-surface': '#f2f0f0',
        tertiary: '#00356a',
        'surface-container-low': '#f5f3f3',
        'on-secondary-fixed-variant': '#7b2f00',
        background: '#ffffff',
        'on-secondary': '#ffffff',
        secondary: '#ef7d00',
        'outline-variant': '#c2c6d2',
        'on-tertiary-fixed': '#001b3c',
        surface: '#ffffff',
        'secondary-container': '#ef7d00',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e4e2e2',
        'on-primary-fixed-variant': '#044787',
        'inverse-surface': '#303031',
        'surface-bright': '#ffffff',
        outline: '#737781',
        'on-error': '#ffffff',
        'secondary-fixed': '#ffdbcc',
        'primary-fixed': '#d5e3ff',
        'primary-container': '#104c8c',
        'surface-dim': '#dbdad9',
        'tertiary-container': '#004b93',
        'surface-tint': '#2c5fa0',
        'on-primary-fixed': '#001c3b',
        'on-secondary-container': '#5e2200',
        'tertiary-fixed-dim': '#a8c8ff',
        'surface-container-high': '#e9e8e7',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#d6e3ff',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#351000',
        'on-surface-variant': '#424750',
        'surface-variant': '#e4e2e2',
        'surface-container': '#efeded',
        'on-primary-container': '#95beff',
        'on-tertiary-fixed-variant': '#00468a',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#96bdff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-manrope)', 'sans-serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
        manrope: ['var(--font-manrope)', 'sans-serif'],
        barlow: ['var(--font-barlow-condensed)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
